### ISSUE TITLE
ReferenceError when using junit reporter in 0.11.0

### ISSUE THREAD

**Issue by aeisenberg** [caolan/nodeunit#338]
After the upgrade to 0.11.0, I am getting the following error when trying to use the junit reporter. When I downgrade back to 0.10.0, I not longer get the error.

```
ReferenceError: ejs:2
    1| <?xml version="1.0" encoding="UTF-8" ?>
 >> 2| <% for (var i=0; i < suites.length; i++) { %>
    3|   <% var suite=suites[i]; %>
    4|   <testsuite name="<%= suite.name %>"
    5|              errors="<%= suite.errorCount %>"

suites is not defined
    at eval (eval at compile (/.../node_modules/ejs/lib/ejs.js:482:12), <anonymous>:11:26)
    at returnedFn (/.../node_modules/ejs/lib/ejs.js:513:17)
    at Object.exports.render (/.../node_modules/ejs/lib/ejs.js:316:37)
    at /.../node_modules/nodeunit/lib/reporters/junit.js:150:44
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

I will try to create a simple project that reproduces the error.

**Comment by aeisenberg** [comment]
I am attaching a simple project. To reproduce:

1. tar xvf node-error.zip (yes, this is a TAR file, not a ZIP file. github does not let me upload files with *.tar extension)
2. cd node-error
3. npm i
4. npm test

The test fails with the error above.
[nodeunit-error.zip](https://github.com/caolan/nodeunit/files/771686/nodeunit-error.zip)

**Comment by aeisenberg** [comment]
I have a fix in the PR. Should I create a test for this? I do not see any unit tests for the reporters.

**Comment by aeisenberg** [comment]
Wonder if someone could take a look at this. The fix is simple. This bug is preventing us from upgrading to the latest version.

**Comment by aeisenberg** [comment]
This change is merged. Issue is closed.
