### ISSUE TITLE
make test on fresh clone failes due to undeclared dependencies

### ISSUE THREAD

**Issue by mlda065** [caolan/nodeunit#351]
# Steps to reproduce

```
git clone https://github.com/caolan/nodeunit.git
cd nodeunit
make test
```

# Expected behaviour

All tests pass

# Actual behaviour

```
nodejs ./bin/nodeunit test             
module.js:471                          
    throw err;                         
    ^                                  
                                       
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)                                
    at Module.require (module.js:497:17)                                       
    at require (internal/module.js:20:19)                                      
    at Object.<anonymous> (/home/matthew/Documents/Projects/nodeunit/nodeunit/lib/reporters/junit.js:18:11)
    at Module._compile (module.js:570:32)                                                                                                                      
    at Object.Module._extensions..js (module.js:579:10)                        
    at Module.load (module.js:487:32)                                          
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Makefile:148: recipe for target 'test' failed                                  
make: *** [test] Error 1                      
```

# Commentary

The make script should run `npm install ejs`, since that's a dependency.

I'm new to nodejs and Make files, so I'm not quite sure how to do this.

**Comment by brodybits** [comment]
Isn't the normal procedure to do `npm i` (short for `npm install`) before `npm test`?
